source:[
  "src/signals"
  "src/std"
  "src/keys"
  "src/module"
  "src/mixins"
  "src/widgets"
  "src/container"
  "src/textinput"
  "src/checkbox"
  "src/radio"
  "src/radiogroup"
  "src/colorpicker"
]
test:"test/test-colorpicker"
